### ISSUE TITLE
Comment bubbles not collapsing on dev.blawx.com

### ISSUE THREAD

**Issue by foxcoleman** [Lexpedite/blawx#559]
If I write comments on my local version of Blawx, close them, save them, and re-upload them on the server, they are automatically opened are not collapsible. This problem seems to happen on both the Blawx server and the local version, but in different ways.

**Comment by Gauntlet173** [comment]
Thanks! Check out #457 and let me know if this is something different.

**Comment by foxcoleman** [comment]
Yep, same issue!​
Martin F. Perron
*Please note I only check my personal emails once a day on weekdays*



Jun 27, 2023, 17:26 by ***@***.***:
