### ISSUE TITLE
Problem running test in the Scenario Editor using the "any" object selector

### ISSUE THREAD

**Issue by foxcoleman** [Lexpedite/blawx#561]
Click on "everything_test", run the scenario editor, and note the last saved fact ("physical activity activity_A is a any project_type project"). If I run the test as such, I get a "No answers" result. However, if I run the same test for each individual object on their own, I get the correct/expected results.

Note: I wasn't able to upload the **_.blawx_** file, so I saved it as a **_.txt_** file instead. Let me know if there's a better way of sending this in the future. Thanks!

[PhysicalActivitesRegulations.txt](https://github.com/Lexpedite/blawx/files/11884347/PhysicalActivitesRegulations.txt)

**Comment by Gauntlet173** [comment]
when given the fact 
```
{
      "from_ontology": false,
      "type": "true",
      "attribute": "project_type",
      "object": "activity_A",
      "value": {
        "variable": "value"
      }
    }
```
reasoner.py is placing `project_type(activity_A,{'variable': 'value'})` in the encoding, where it should be `project_type(activity_A,X)` or similar. Problem seems to be with the `even_newer_json_2_scasp` function.

**Comment by Gauntlet173** [comment]
resolved in the issue 543 branch
