### ISSUE TITLE
No "Add Fact" button in Scenario Editor interface

### ISSUE THREAD

**Issue by foxcoleman** [Lexpedite/blawx#566]
I added a new section to my rule and made some change sin my original code as I integrated them together. While all of my individual unit tests work, my Scenario Editor test does not. Here is a picture showing the error messages that come up.

![image](https://github.com/Lexpedite/blawx/assets/55117702/3adfa491-3751-453b-9123-3e0302ae8f28)

**Comment by foxcoleman** [comment]
Bug solved! I used a "-" in one of my attribute names, and once I removed it, the "Add Fact" button returned.

**Comment by Gauntlet173** [comment]
That problem is in the list already as #325, closing this one as duplicate.
